# Generated by Django 5.1.15 on 2026-06-02 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending_approval', max_length=20)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('specialties', models.JSONField(default=list)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('completed_bookings', models.IntegerField(default=0)),
                ('certificate_urls', models.JSONField(default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_therapists', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'therapists_therapistprofile',
                'indexes': [models.Index(fields=['status'], name='therapists__status_de1481_idx'), models.Index(fields=['rating'], name='therapists__rating_026e98_idx')],
            },
        ),
    ]
