# Generated by Django 6.0.5 on 2026-06-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Giới thiệu bản thân'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Trạng thái online'),
        ),
    ]
