# Generated by Claude Code

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_therapistprofile_bio_therapistprofile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='citizen_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Số CCCD 12 chữ số', max_length=12),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='portrait_url',
            field=models.URLField(blank=True, default='', help_text='URL ảnh chân dung'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='citizen_id_front_url',
            field=models.URLField(blank=True, default='', help_text='URL ảnh CCCD mặt trước'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='citizen_id_back_url',
            field=models.URLField(blank=True, default='', help_text='URL ảnh CCCD mặt sau'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='service_areas',
            field=models.JSONField(default=list, help_text='Khu vực phục vụ tại Đà Nẵng'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='has_transport',
            field=models.BooleanField(default=False, help_text='Có phương tiện di chuyển'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='has_equipment',
            field=models.BooleanField(default=False, help_text='Có dụng cụ hành nghề'),
        ),
    ]
