# Generated by Claude Code

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0003_add_therapist_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='pending_citizen_id',
            field=models.CharField(blank=True, default='', help_text='Số CCCD đang chờ duyệt', max_length=12),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='pending_citizen_id_front_url',
            field=models.URLField(blank=True, default='', help_text='URL ảnh CCCD mặt trước đang chờ duyệt'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='pending_citizen_id_back_url',
            field=models.URLField(blank=True, default='', help_text='URL ảnh CCCD mặt sau đang chờ duyệt'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='pending_certificate_urls',
            field=models.JSONField(default=list, help_text='Danh sách chứng chỉ đang chờ duyệt'),
        ),
    ]
