[pytest]
DJANGO_SETTINGS_MODULE = jvj_api.settings.development
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short -v --reuse-db --no-migrations
