# Generated by Django 6.0.5 on 2026-06-02 10:32

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('neck_shoulder', 'Cổ vai gáy'), ('physical_therapy', 'Vật lý trị liệu'), ('recovery', 'Phục hồi chức năng'), ('acupressure', 'Ấn huyệt'), ('traditional_medicine', 'Đông y')], max_length=30)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('duration_minutes', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('review_count', models.IntegerField(default=0)),
                ('image_url', models.URLField(max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='spas.spa')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'treatments_treatment',
                'ordering': ['-rating', '-created_at'],
                'indexes': [models.Index(fields=['therapist'], name='treatments__therapi_1a3c82_idx'), models.Index(fields=['category'], name='treatments__categor_bf2f97_idx'), models.Index(fields=['is_available'], name='treatments__is_avai_d87ad0_idx'), models.Index(fields=['rating'], name='treatments__rating_dd1202_idx')],
            },
        ),
    ]
