# Generated by Django 5.1.15 on 2026-06-03 21:50

from django.db import migrations, models


def migrate_image_url_to_images(apps, schema_editor):
    """Migrate existing image_url to images array."""
    Treatment = apps.get_model('treatments', 'Treatment')
    for treatment in Treatment.objects.all():
        if treatment.image_url:
            treatment.images = [treatment.image_url]
            treatment.save(update_fields=['images'])


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='images',
            field=models.JSONField(default=list, help_text='Array of image URLs, max 5. First image is the main image.'),
        ),
        migrations.RunPython(migrate_image_url_to_images, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='treatment',
            name='image_url',
        ),
    ]
