# Generated by Django 5.1.15 on 2026-06-11 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('reviews', '0001_initial'),
        ('treatments', '0002_remove_treatment_image_url_treatment_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('customer', 'treatment'), name='unique_customer_treatment_review'),
        ),
    ]
