# Generated by Django 6.0.5 on 2026-06-02 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('vnpay_qr', 'VNPAY QR'), ('vnpay_card', 'VNPAY Card')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('vnpay_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('vnpay_response_code', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('tone', models.CharField(choices=[('neutral', 'Neutral'), ('success', 'Success'), ('warning', 'Warning')], default='neutral', max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='payments.payment')),
            ],
            options={
                'db_table': 'payments_paymenttimeline',
                'ordering': ['occurred_at'],
            },
        ),
    ]
