# Generated by Django 6.0.5 on 2026-06-02 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('disabled', 'Disabled')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='treatments.treatment')),
            ],
            options={
                'db_table': 'timeslots_timeslot',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['therapist', 'date'], name='timeslots_t_therapi_19599d_idx'), models.Index(fields=['status'], name='timeslots_t_status_15d48e_idx')],
                'constraints': [models.UniqueConstraint(fields=('therapist', 'date', 'start_time'), name='unique_therapist_date_start')],
            },
        ),
    ]
