# Generated by Django 5.1.15 on 2026-06-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0001_initial'),
        ('treatments', '0002_remove_treatment_image_url_treatment_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='treatments.treatment'),
        ),
    ]
